export const IS_PROFILE_LOADING = "IS_PROFILE_LOADING";
export const IS_LOADING_PROFILE_SUCCESS = "IS_LOADING_PROFILE_SUCCESS";
export const IS_LOADING_PROFILE_FAILURE = "IS_LOADING_PROFILE_FAILURE";
