export const IS_PROJECT_LOADING = "IS_PROJECT_LOADING";
export const IS_LOADING_PROJECT_SUCCESS = "IS_LOADING_PROJECT_SUCCESS";
export const IS_LOADING_PROJECT_FAILURE = "IS_LOADING_PROJECT_FAILURE";
